global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rapid-crud-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Docker 容器访问宿主机服务
