package com.rapidcrud.generator.mongo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@Document(collection = "audit_logs")
@Schema(description = "Audit log document stored in MongoDB")
public class AuditLogDocument {
    @Id
    @Schema(description = "MongoDB autogenerated ID")
    private String id;

    @Schema(description = "Action performed, e.g., GENERATE, UPDATE, DELETE")
    private String action;

    @Schema(description = "Entity name related to the action, e.g., User, Product")
    private String entity;

    @Schema(description = "Original request payload or metadata in JSON format")
    private String payload;

    @Schema(description = "Timestamp when the action occurred")
    private LocalDateTime timestamp;
}

